[package]
name = "paynow"
version = "0.1.0"
authors = ["sabelo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
serde = "1.0.103"
serde_urlencoded = "0.6.1"
